### ISSUE TITLE
cmake configuration setup

### ISSUE THREAD

**Issue by rcompier** [Deluze/qpang-essence-emulator#1]
Hey Deluze, I know you don't work on this anymore and everything surrounding it but I still wanted to ask if you could give some help.
Didn't know another place to contact you that wasn't too formal.

I've currently have the base project and all the requirements installed.

Cmake couldn't find boost the first time after installing it with vcpkg so I manually installed it which seems to work. 
First I tried setting it up with a XAMPP MySQL server which didn't work, so I installed MySQL standalone and add a param to the cmake command: `-DMYSQL_ROOT:STRING=` which got me a step closer.

Now it says it's failing to run the MSBuild command even though it's installed from the Visual Studio Installer. The `msbuild` command does work in a cmdlet and having it added to the system variable `PATH`.

Would you ever have the time and be down to help and take a look with me on how to set it up?
I've asked some other former people who also worked on it but they either said that you set up this part or they don't remember.

**Comment by Deluze** [comment]
Pfff, it must've been at least 4+ years since this README was actually written.

> Cmake couldn't find boost the first time after installing it with vcpkg

This is actually not documented in the readme, but..
Make sure the vcpkg packages are installed with the `x86-windows` triplet, e.g.:

```bash
vcpkg install --triplet=x86-windows spdlog
```

And make sure you pass down vcpkg's toolchain file to CMake:

```bash
cmake .. -DCMAKE_TOOLCHAIN_FILE=<path_to_vcpkg_toolchain_file>
```

alternatively you can set the `VCPKG_ROOT` environment variable, looking at the CMakeLists.txt:

```cmake
if(DEFINED ENV{VCPKG_ROOT} AND NOT DEFINED CMAKE_TOOLCHAIN_FILE)
   set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake")
endif()
```

More info: https://learn.microsoft.com/en-us/vcpkg/users/buildsystems/cmake-integration.

> First I tried setting it up with a XAMPP MySQL server which didn't work

Does the MySQL server that comes with XAMPP actually bundle the .lib and header files to develop with?
There's a a `FindMySQL.cmake` script that checks the default MySQL connector installation path to see if the header files, etc. are present. If the MySQL connector wasn't downloaded through the regular connector installer, I think you'd need to extend the script to look into a different path. Make sure it's the 32-bit version though, you're gonna have to look through the archives as the current connectors are 64-bit only.

> Now it says it's failing to run the MSBuild command even though it's installed from the Visual Studio Installer

If you post the logs maybe we can deduce the error.

This is pretty legacy stuff from a time where I was completely new to C++ & CMake. I know I was able to generate project files like a year ago, so I can tell you it's still possible to do so today. I uploaded the binaries in the release in case you just want to run the server without changing the source code: https://github.com/Deluze/qpang-essence-emulator/releases/tag/v1

GL with the server crashes though :-) and don't be too harsh on the code.

**Comment by rcompier** [comment]
Since I don't have a need to edit the source code I used the already build version and after some tinkering it's running locally.
I'll still try to use some of your suggestions just to see if I could get it working.

Either way, still thanks for the reply.
